### ISSUE TITLE
Exception catched...

### ISSUE THREAD

**Issue by ZeDvD** [gotenna/PublicSDK#18]
I got the following exception in the SDK

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.contains(java.lang.Object)' on a null object reference
                                                                             at com.gotenna.sdk.user.User.hasGroupGID(SourceFile:280)
                                                                             at com.gotenna.sdk.gids.GIDManager.gidTypeForGID(SourceFile:72)
                                                                             at com.gotenna.sdk.gids.GTGid.initWithBase(SourceFile:49)
                                                                             at com.gotenna.sdk.commands.a.a(SourceFile:405)
                                                                             at com.gotenna.sdk.commands.GTCommandCenter.sendEchoCommand(SourceFile:117)
                                                                             at com.gotenna.sdk.bluetooth.GTConnectionManager.b(SourceFile:404)
                                                                             at com.gotenna.sdk.bluetooth.GTConnectionManager.d(SourceFile:43)
                                                                             at com.gotenna.sdk.bluetooth.GTConnectionManager$6.run(SourceFile:621)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by ZeDvD** [comment]
I had to uninstall then reinstall my app to make this error disappear. I think there is a conflict in the userDatastore or any other local storage.

**Comment by tcolligan-ap** [comment]
@ZeDvD Sounds like the user object may have gotten corrupted somehow. Will look into the issue and keep you updated. We should be releasing an SDK update to support the goTenna Mesh soon enough, and will roll fixes into that if necessary. Thanks!

**Comment by ZeDvD** [comment]
What are the SDK differences for Gotenna Mesh ? I ordered two of them, and hope the current SDK is compatible with mesh (I hope I won't have to update my app...)

**Comment by tcolligan-ap** [comment]
@ZeDvD The current SDK is not compatible with Mesh unfortunately. We are working on updates to make it compatible. It should require a minimal amount of changes from your side, most of the changes we are working on will be buried deep down in the SDK. 

The changes you will see will mainly be in `GTConnectionManager.scanAndConnect()` there will be a parameter to specify whether you wish to connect to a goTenna Mesh or V1 goTenna.

The goTenna Mesh advertises using a different BLE UUID, so the current SDK will not be able to find it.

Also one more clarification to avoid confusion, goTenna V1 is not compatible with goTenna Mesh as they operate on completely different frequency spectrums. The V1 on the 150 MHZ band and the Mesh on the 900 MHz band. If you send a message on the goTenna V1, the goTenna Mesh will not receive it, and visa versa.

Hope that helps

**Comment by tcolligan-ap** [comment]
@ZeDvD This exception should be fixed in the latest sdk release v2.0, if you still run into issues let us know!
