### ISSUE TITLE
ExceptionInitializerError in UserDataStore

### ISSUE THREAD

**Issue by chriscrosscutler** [gotenna/PublicSDK#28]
I keep getting this error when trying to use the UserDataStore class. Looks like it's getting a null pointer when the UserDataStore is trying to access a SharedPreference?

Stack Trace:
java.lang.ExceptionInInitializerError

at com.gotenna.sdk.user.UserDataStore$a.a(SourceFile:43)
at com.gotenna.sdk.user.UserDataStore.getInstance(SourceFile:55)
at com.chriscutler.stracker.scan.ScanPresenter.<init>(ScanPresenter.java:25)
at com.chriscutler.stracker.scan.ScanActivity.onCreate(ScanActivity.java:58)
at android.app.Activity.performCreate(Activity.java:6679)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6119)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
at com.gotenna.sdk.user.UserDataStore.a(SourceFile:144)
at com.gotenna.sdk.user.UserDataStore.<init>(SourceFile:40)
at com.gotenna.sdk.user.UserDataStore.<init>(SourceFile:23)
at com.gotenna.sdk.user.UserDataStore$a.<clinit>(SourceFile:45)
at com.gotenna.sdk.user.UserDataStore$a.a(SourceFile:43) 
at com.gotenna.sdk.user.UserDataStore.getInstance(SourceFile:55) 
at com.chriscutler.stracker.scan.ScanPresenter.<init>(ScanPresenter.java:25) 
at com.chriscutler.stracker.scan.ScanActivity.onCreate(ScanActivity.java:58) 
at android.app.Activity.performCreate(Activity.java:6679) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
at android.app.ActivityThread.-wrap12(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:154) 
at android.app.ActivityThread.main(ActivityThread.java:6119) 
at java.lang.reflect.Method.invoke(Native Method)

**Comment by tcolligan-ap** [comment]
@chriscrosscutler This is happening in the sample app that you are using? Are your own application? It looks like that is pointing to this line in the SDK `SharedPreferences prefs = GoTenna.getContext().getSharedPreferences(SHARED_PREFS_NAME, Context.MODE_PRIVATE);`

Which makes me think the `getContext()` function is returning `null`.

The context should be supplied when you call the setup function `Gotenna.setApplicationToken(` Can you tell me at what point in your application lifecycle you are calling `setApplicationToken` and with what kind of context?

**Comment by chriscrosscutler** [comment]
@tcolligan-ap you were right. `getContext()` was returning null because I wasn't calling `Gotenna.setApplicationToken()`. Looks like this was an error on my end.
