### ISSUE TITLE
gotenna library bug

### ISSUE THREAD

**Issue by ThreeSixes** [gotenna/PublicSDK#45]
Hello, I have been trying to run the provided Python driver REPL for the antenna after installing the Python2 and 3 libraries via pip and creating a settings file for use with a GoTenna mesh connected via USB. I've got the settings.json populated with the following:
```
{
    "sdk_token":    "[REDACTED]",
    "mesh":
    {   
        "geo_settings":
        {
            "region": 1
        }
    }   
}

```

And when I try to run `python sampleDriver.py -s setting.json` I get the following trace:

```
Traceback (most recent call last):
  File "sampleDriver.py", line 19, in <module>
    import goTenna
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/__init__.py", line 21, in <module>
    from goTenna import device
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 31, in <module>
    import goTenna.message
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/message.py", line 13, in <module>
    from goTenna.tlv import message_tlv
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/tlv/__init__.py", line 23, in <module>
    from goTenna.tlv import l1l1l1l1ll_opy_
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/tlv/l1l1l1l1ll_opy_.py", line 299
    l11ll_opy_ (u"ࠨࡲࡵ࡭ࡻࡧࡴࡦ࠿ࡾࢁ࠱ࠦࡥ࡮ࡧࡵ࡫ࡪࡴࡣࡺ࠿ࡾࢁࡃ࠭஄") \
             ^
SyntaxError: invalid syntax
```
There's also a bug here:
```
Traceback (most recent call last):
  File "sampleDriver.py", line 19, in <module>
    import goTenna
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/__init__.py", line 25, in <module>
    from goTenna import driver_backend
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 399
    l11ll_opy_ (u"ࠨ࡛ࡲࡹࠥࡳࡵࡴࡶࠣࡹࡸ࡫ࠠࡧ࡫ࡵࡱࡼࡧࡲࡦࠢࡁࠤࢀࢃࠠࡢࡰࡧࠤࡁࡃࠠࡼࡿࠪੳ")
             ^
SyntaxError: invalid syntax
```
Has anyone else had problems with the library exploding? I get the same exception with both the Python 2 and 3 libraries attempting to run the REPL and attempting to include it in my own code. I've also had the same problem with all the sample code or anything I've written that imports the library.

**Comment by ThreeSixes** [comment]
Looks like your driver has another syntax error:
```
Traceback (most recent call last):
  File "sampleDriver.py", line 19, in <module>
    import goTenna
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/__init__.py", line 25, in <module>
    from goTenna import driver_backend
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 399
    l11ll_opy_ (u"ࠨ࡛ࡲࡹࠥࡳࡵࡴࡶࠣࡹࡸ࡫ࠠࡧ࡫ࡵࡱࡼࡧࡲࡦࠢࡁࠤࢀࢃࠠࡢࡰࡧࠤࡁࡃࠠࡼࡿࠪੳ")
             ^
SyntaxError: invalid syntax

```

**Comment by ThreeSixes** [comment]
I'd open a PR to fix this, but I don't have access to the code you used to build the wheel modules. In the case of line 299 in `/goTenna/tlv/l1l1l1l1ll_opy_.py` AND in the case of line 399 of `goTenna/driver_backend.py` there's a missing `.` on the next line that's broken by the `\`.

The PDF is also missing the fact that you need to `pip install spidev` before running the code whether or not you're using the SPI bus.

**Comment by warren-r** [comment]
Hi,
We are working on this issue and will provide an update soon.

**Comment by warren-r** [comment]
Please use SDK version 0.12.5
