### ISSUE TITLE
Unable to interface with GoTenna Mesh with firmware version 1.1.12 via USB

### ISSUE THREAD

**Issue by ThreeSixes** [gotenna/PublicSDK#46]
$ python sample.py
Welcome to the goTenna API sample! Press ? for a command list.
You must begin by entering an SDK token with the sdk_token command.
goTenna>sdk_token <INSERT MY TOKEN HERE>
goTenna>device_present: devices present: 900 MX1802[XXXX] on /dev/ttyACM0
Device physically connected, configure to continue
set_geo_region 1
region=1
goTenna>set_gid 111111111111
goTenna>can_connect
GID: OK
PRO - TX Power: Not Set
PRO - Frequencies: Not Set
PRO - Bandwidth: Not Set
MESH - Geo region: OK
goTenna>ERROR:goTenna.driver.Driver:Error during device handshake!
Traceback (most recent call last):
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 264, in _11l111lll_opy_
    self._device_specifics[device_type][l11ll_opy_ (u"ࠩࡶࡩࡹࡻࡰࠨ੊")]()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 245, in _11ll1ll1l_opy_
    self.device.l1l1ll11ll_opy_(self._storage.groups.values(), self._settings.geo_settings)
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 534, in l1l1ll11ll_opy_
    self.echo()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 260, in echo
    self._1ll1ll111_opy_(l1ll1ll1l1_opy_, command)
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 448, in _1ll1ll111_opy_
    (now-l1l11l1l1_opy_).total_seconds())
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 218, in read_binary_blocking
    for to_return in l1l111ll1_opy_:
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 190, in l11ll1ll1_opy_
    l1l1l1111_opy_()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 188, in l1l1l1111_opy_
    (now-l1l11l1l1_opy_).seconds)
TimeoutException: GoTenna communication timed out after 10s. Command: read_binary
ERROR:goTenna.driver.Driver:Error during device handshake!
Traceback (most recent call last):
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 264, in _11l111lll_opy_
    self._device_specifics[device_type][l11ll_opy_ (u"ࠩࡶࡩࡹࡻࡰࠨ੊")]()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 245, in _11ll1ll1l_opy_
    self.device.l1l1ll11ll_opy_(self._storage.groups.values(), self._settings.geo_settings)
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 534, in l1l1ll11ll_opy_
    self.echo()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 260, in echo
    self._1ll1ll111_opy_(l1ll1ll1l1_opy_, command)
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 448, in _1ll1ll111_opy_
    (now-l1l11l1l1_opy_).total_seconds())
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 218, in read_binary_blocking
    for to_return in l1l111ll1_opy_:
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 190, in l11ll1ll1_opy_
    l1l1l1111_opy_()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 188, in l1l1l1111_opy_
    (now-l1l11l1l1_opy_).seconds)
TimeoutException: GoTenna communication timed out after 10s. Command: read_binary
ERROR:goTenna.driver.Driver:Error during device handshake!
Traceback (most recent call last):
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 264, in _11l111lll_opy_
    self._device_specifics[device_type][l11ll_opy_ (u"ࠩࡶࡩࡹࡻࡰࠨ੊")]()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 245, in _11ll1ll1l_opy_
    self.device.l1l1ll11ll_opy_(self._storage.groups.values(), self._settings.geo_settings)
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 534, in l1l1ll11ll_opy_
    self.echo()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 260, in echo
    self._1ll1ll111_opy_(l1ll1ll1l1_opy_, command)
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 448, in _1ll1ll111_opy_
    (now-l1l11l1l1_opy_).total_seconds())
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 218, in read_binary_blocking
    for to_return in l1l111ll1_opy_:
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 190, in l11ll1ll1_opy_
    l1l1l1111_opy_()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 188, in l1l1l1111_opy_
    (now-l1l11l1l1_opy_).seconds)
TimeoutException: GoTenna communication timed out after 10s. Command: read_binary

**Comment by warren-r** [comment]
On Linux, the modem manager deamon might try to capture the goTenna USB link making the SDK connection fail with a timeout error. In this case, copy the 77-gotenna.rules in /etc/udev/rules.d for the modem manager to ignore the goTenna devices.

Note: 77-gotenna.rules file is provided with SDK

**Comment by ThreeSixes** [comment]
The udev rules provided with the package have been copied to `/etc/udev/rules.d/` on both hosts.

**Comment by warren-r** [comment]
Ok we will look into it and get back to you. I am assuming you already tried rebooting your machine. We have tried with 18.0.4.

**Comment by ThreeSixes** [comment]
There have been a number of reboots on both hosts since I went throught the setup procedure with the same error messages. I'll see if there's anything else on the hosts trying to claim the serial port besides the modem/network manager.

**Comment by ThreeSixes** [comment]
So I tried a few more things including installing completely stopping the Modem Manager on my Ubuntu 18.0.4 host and got the same results. I also installed the SDK on a Raspberry Pi. Same error messages there too after installing the udev rules and rebooting, etc. I had also noticed on all three hosts I'd get these error messages in dmesg when I'd try to use the SDK:

```
[  926.486586] usb 1-1.1.2: new full-speed USB device number 7 using dwc_otg
[  926.619934] usb 1-1.1.2: New USB device found, idVendor=1fc9, idProduct=8182
[  926.619947] usb 1-1.1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  926.619955] usb 1-1.1.2: Product:  GOTENNA 900
[  926.619964] usb 1-1.1.2: Manufacturer: GOTENNA
[  926.619972] usb 1-1.1.2: SerialNumber: MX1802XXXX
[  926.666503] cdc_acm 1-1.1.2:1.0: ttyACM0: USB ACM device
[  926.667388] usbcore: registered new interface driver cdc_acm
[  926.667396] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters
[ 3705.430542] cdc_acm 1-1.1.2:1.0: failed to set dtr/rts
[ 3715.499067] cdc_acm 1-1.1.2:1.0: failed to set dtr/rts
[ 3715.544799] cdc_acm 1-1.1.2:1.0: failed to set dtr/rts
[ 3721.736178] cdc_acm 1-1.1.2:1.0: failed to set dtr/rts
```

I'm not sure of those failed to set dtr/rts messages are relevant.

**Comment by warren-r** [comment]
I ran into same issue on a Ubuntu 18.04.1 LTS fresh iso installation. To me it looked like the system did not have any serial driver to handle any serial device. So I had to do sudo apt-get upgrade/update. After this mesh started connecting to usb-serial (/dev/ttyACM0) 
[INFO:2019-01-10 15:07:25,668:goTenna.driver.Driver] Connected to device MX99999901 on /dev/ttyACM0
[INFO:2019-01-10 15:07:25,669:__main__] connect: port: /dev/ttyACM0 serial: MX99999901 type: 900 firmware version: (1, 1, 12)
Can you please try the same?
kernel version: 4.15.0-43-generic #46-Ubuntu

**Comment by warren-r** [comment]
Not sure what the problem is. We had a typo in 77-gotenna.rules 
ATTRS{idVendor}=="1fc9", ATTRS(idProduct}=="8182", ENV{ID_MM_DEVICE_IGNORE}="1"
I assumed that you corrected this.
Also can you send me your uname -a output?

**Comment by ThreeSixes** [comment]
I fixed the udev entry, and had missed the typo until you mentioned it (derp). After a reboot I'm still having the same problem. I've also stopped the modem manager just in case, and `uname -a` gives:
`Linux workstation 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`. Are there any packages or package versions I could be checking for?

**Comment by ThreeSixes** [comment]
I also pulled master before testing, and it only had IOS file updates.

Test output:
```
 python sample.py 
Welcome to the goTenna API sample! Press ? for a command list.
You must begin by entering an SDK token with the sdk_token command.
goTenna>sdk_token [REDACTED]
goTenna>device_present: devices present: 900 MX180[REDACTED] on /dev/ttyACM0
Device physically connected, configure to continue
set_gid 12345678909876
goTenna>set_geo_region 1
region=1
goTenna>send_broadcast "Hello, wERROR:goTenna.driver.Driver:Error during device handshake!
Traceback (most recent call last):
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 264, in _11l111lll_opy_
    self._device_specifics[device_type][l11ll_opy_ (u"ࠩࡶࡩࡹࡻࡰࠨ੊")]()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 245, in _11ll1ll1l_opy_
    self.device.l1l1ll11ll_opy_(self._storage.groups.values(), self._settings.geo_settings)
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 534, in l1l1ll11ll_opy_
    self.echo()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 260, in echo
    self._1ll1ll111_opy_(l1ll1ll1l1_opy_, command)
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 448, in _1ll1ll111_opy_
    (now-l1l11l1l1_opy_).total_seconds())
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 218, in read_binary_blocking
    for to_return in l1l111ll1_opy_:
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 190, in l11ll1ll1_opy_
    l1l1l1111_opy_()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 188, in l1l1l1111_opy_
    (now-l1l11l1l1_opy_).seconds)
TimeoutException: GoTenna communication timed out after 10s. Command: read_binary
orld"
No device connected
goTenna>ERROR:goTenna.driver.Driver:Error during device handshake!
Traceback (most recent call last):
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 264, in _11l111lll_opy_
    self._device_specifics[device_type][l11ll_opy_ (u"ࠩࡶࡩࡹࡻࡰࠨ੊")]()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 245, in _11ll1ll1l_opy_
    self.device.l1l1ll11ll_opy_(self._storage.groups.values(), self._settings.geo_settings)
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 534, in l1l1ll11ll_opy_
    self.echo()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 260, in echo
    self._1ll1ll111_opy_(l1ll1ll1l1_opy_, command)
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 448, in _1ll1ll111_opy_
    (now-l1l11l1l1_opy_).total_seconds())
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 218, in read_binary_blocking
    for to_return in l1l111ll1_opy_:
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 190, in l11ll1ll1_opy_
    l1l1l1111_opy_()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 188, in l1l1l1111_opy_
    (now-l1l11l1l1_opy_).seconds)
TimeoutException: GoTenna communication timed out after 10s. Command: read_binary
Traceback (most recent call last):
  File "sample.py", line 853, in <module>
    run_cli()
  File "sample.py", line 844, in run_cli
    cli_obj.cmdloop("Welcome to the goTenna API sample! "
  File "/usr/lib/python2.7/cmd.py", line 130, in cmdloop
    line = raw_input(self.prompt)
KeyboardInterrupt
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^CERROR:goTenna.driver.Driver:Error during device handshake!
Traceback (most recent call last):
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 264, in _11l111lll_opy_
    self._device_specifics[device_type][l11ll_opy_ (u"ࠩࡶࡩࡹࡻࡰࠨ੊")]()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 245, in _11ll1ll1l_opy_
    self.device.l1l1ll11ll_opy_(self._storage.groups.values(), self._settings.geo_settings)
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 534, in l1l1ll11ll_opy_
    self.echo()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 260, in echo
    self._1ll1ll111_opy_(l1ll1ll1l1_opy_, command)
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 448, in _1ll1ll111_opy_
    (now-l1l11l1l1_opy_).total_seconds())
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 218, in read_binary_blocking
    for to_return in l1l111ll1_opy_:
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 190, in l11ll1ll1_opy_
    l1l1l1111_opy_()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 188, in l1l1l1111_opy_
    (now-l1l11l1l1_opy_).seconds)
TimeoutException: GoTenna communication timed out after 10s. Command: read_binary
Exception KeyboardInterrupt in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
```

and dmesg is still giving this:

```
[  484.989550] usb 2-2: USB disconnect, device number 4
[  491.941407] usb 2-1: new full-speed USB device number 5 using xhci_hcd
[  492.090613] usb 2-1: New USB device found, idVendor=1fc9, idProduct=8182
[  492.090617] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  492.090620] usb 2-1: Product:  GOTENNA 900
[  492.090622] usb 2-1: Manufacturer: GOTENNA
[  492.090625] usb 2-1: SerialNumber: MX18022173
[  492.091248] cdc_acm 2-1:1.0: ttyACM0: USB ACM device
[  912.314686] cdc_acm 2-1:1.0: failed to set dtr/rts
[  922.336689] cdc_acm 2-1:1.0: failed to set dtr/rts
[  922.352126] cdc_acm 2-1:1.0: failed to set dtr/rts
[  932.373955] cdc_acm 2-1:1.0: failed to set dtr/rts
[  932.391704] cdc_acm 2-1:1.0: failed to set dtr/rts
[  942.415501] cdc_acm 2-1:1.0: failed to set dtr/rts
```

The `cdc_acm 2-1:1.0: failed to set dtr/rts` starts happening when the SDK connects. I have the same error message when I stop the modem manager.

**Comment by ThreeSixes** [comment]
I also pulled master before testing, and it only had IOS file updates.

Test output:
```
 python sample.py 
Welcome to the goTenna API sample! Press ? for a command list.
You must begin by entering an SDK token with the sdk_token command.
goTenna>sdk_token [REDACTED]
goTenna>device_present: devices present: 900 MX180[REDACTED] on /dev/ttyACM0
Device physically connected, configure to continue
set_gid 12345678909876
goTenna>set_geo_region 1
region=1
goTenna>send_broadcast "Hello, wERROR:goTenna.driver.Driver:Error during device handshake!
Traceback (most recent call last):
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 264, in _11l111lll_opy_
    self._device_specifics[device_type][l11ll_opy_ (u"ࠩࡶࡩࡹࡻࡰࠨ੊")]()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 245, in _11ll1ll1l_opy_
    self.device.l1l1ll11ll_opy_(self._storage.groups.values(), self._settings.geo_settings)
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 534, in l1l1ll11ll_opy_
    self.echo()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 260, in echo
    self._1ll1ll111_opy_(l1ll1ll1l1_opy_, command)
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 448, in _1ll1ll111_opy_
    (now-l1l11l1l1_opy_).total_seconds())
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 218, in read_binary_blocking
    for to_return in l1l111ll1_opy_:
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 190, in l11ll1ll1_opy_
    l1l1l1111_opy_()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 188, in l1l1l1111_opy_
    (now-l1l11l1l1_opy_).seconds)
TimeoutException: GoTenna communication timed out after 10s. Command: read_binary
orld"
No device connected
goTenna>ERROR:goTenna.driver.Driver:Error during device handshake!
Traceback (most recent call last):
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 264, in _11l111lll_opy_
    self._device_specifics[device_type][l11ll_opy_ (u"ࠩࡶࡩࡹࡻࡰࠨ੊")]()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 245, in _11ll1ll1l_opy_
    self.device.l1l1ll11ll_opy_(self._storage.groups.values(), self._settings.geo_settings)
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 534, in l1l1ll11ll_opy_
    self.echo()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 260, in echo
    self._1ll1ll111_opy_(l1ll1ll1l1_opy_, command)
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 448, in _1ll1ll111_opy_
    (now-l1l11l1l1_opy_).total_seconds())
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 218, in read_binary_blocking
    for to_return in l1l111ll1_opy_:
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 190, in l11ll1ll1_opy_
    l1l1l1111_opy_()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 188, in l1l1l1111_opy_
    (now-l1l11l1l1_opy_).seconds)
TimeoutException: GoTenna communication timed out after 10s. Command: read_binary
Traceback (most recent call last):
  File "sample.py", line 853, in <module>
    run_cli()
  File "sample.py", line 844, in run_cli
    cli_obj.cmdloop("Welcome to the goTenna API sample! "
  File "/usr/lib/python2.7/cmd.py", line 130, in cmdloop
    line = raw_input(self.prompt)
KeyboardInterrupt
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^CERROR:goTenna.driver.Driver:Error during device handshake!
Traceback (most recent call last):
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 264, in _11l111lll_opy_
    self._device_specifics[device_type][l11ll_opy_ (u"ࠩࡶࡩࡹࡻࡰࠨ੊")]()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/driver_backend.py", line 245, in _11ll1ll1l_opy_
    self.device.l1l1ll11ll_opy_(self._storage.groups.values(), self._settings.geo_settings)
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 534, in l1l1ll11ll_opy_
    self.echo()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 260, in echo
    self._1ll1ll111_opy_(l1ll1ll1l1_opy_, command)
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/device.py", line 448, in _1ll1ll111_opy_
    (now-l1l11l1l1_opy_).total_seconds())
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 218, in read_binary_blocking
    for to_return in l1l111ll1_opy_:
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 190, in l11ll1ll1_opy_
    l1l1l1111_opy_()
  File "/home/xmanj/.local/lib/python2.7/site-packages/goTenna/pcb_connection.py", line 188, in l1l1l1111_opy_
    (now-l1l11l1l1_opy_).seconds)
TimeoutException: GoTenna communication timed out after 10s. Command: read_binary
Exception KeyboardInterrupt in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
```

and dmesg is still giving this:

```
[  484.989550] usb 2-2: USB disconnect, device number 4
[  491.941407] usb 2-1: new full-speed USB device number 5 using xhci_hcd
[  492.090613] usb 2-1: New USB device found, idVendor=1fc9, idProduct=8182
[  492.090617] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  492.090620] usb 2-1: Product:  GOTENNA 900
[  492.090622] usb 2-1: Manufacturer: GOTENNA
[  492.090625] usb 2-1: SerialNumber: MX180[REDACTED]
[  492.091248] cdc_acm 2-1:1.0: ttyACM0: USB ACM device
[  912.314686] cdc_acm 2-1:1.0: failed to set dtr/rts
[  922.336689] cdc_acm 2-1:1.0: failed to set dtr/rts
[  922.352126] cdc_acm 2-1:1.0: failed to set dtr/rts
[  932.373955] cdc_acm 2-1:1.0: failed to set dtr/rts
[  932.391704] cdc_acm 2-1:1.0: failed to set dtr/rts
[  942.415501] cdc_acm 2-1:1.0: failed to set dtr/rts
```

The `cdc_acm 2-1:1.0: failed to set dtr/rts` starts happening when the SDK connects. I have the same error message when I stop the modem manager.

**Comment by ThreeSixes** [comment]
Is there a hardware issue with some of these units? I have three that are bricked from attempting a firmware update to 1.1.8.

**Comment by warren-r** [comment]
I am assuming the unit that you are trying to get the python sdk is upgraded to 1.1.12. Unit MUST be on this firmware version to work with python SDK.
Regarding bricked units, what is the behavior of the LED on these units it is blinking faster? It is not a hardware issue but there is also a bluetooth firmware upgrade when you upgrade to 1.1.8. This may get the unit into a mode that requires retrying firmware upgrade process. It may recover from this state if you try with an apple device (ipad, iphone, ipod etc) . Also you can contact support@gotenna.com if you need further assistance with your units.

**Comment by warren-r** [comment]
I just cloned the repo and see all 3 sdks
![image](https://user-images.githubusercontent.com/10576888/51685791-17cb7300-1fbd-11e9-8211-2ec15415740e.png)
Can you try again?
